<?php

return [
    'paypal' => [
        'enabled' => true,
        'name' => 'Paypal',
        'route' => 'paypal',
        'currency' => 'USD',
        'image' => 'images/paypal.png',
        //'endpoint' => 'https://api-m.paypal.com', // for production
        'endpoint' => 'https://api-m.sandbox.paypal.com', // for sandbox
        'client_id' => 'PAYPAL_CLIENT_ID',
        'client_secret' => 'PAYPAL_CLIENT_SECRET',
        'mode' => 'sandbox', //live, sandbox
        'package' => [
            ['name' => '500 Silk', 'price' => 5, 'type' => 0, 'value' => 500,],
            ['name' => '1000 Silk', 'price' => 10, 'type' => 0, 'value' => 1000,],
            ['name' => '2500 Silk', 'price' => 25, 'type' => 0, 'value' => 2500,],
            ['name' => '5000 Silk', 'price' => 50, 'type' => 0, 'value' => 5000,],
            ['name' => '7500 Silk', 'price' => 75, 'type' => 0, 'value' => 7500,],
            ['name' => '10000 Silk', 'price' => 100, 'type' => 0, 'value' => 10000,],
        ],
    ],
    'stripe' => [
        'enabled' => false,
        'name' => 'Stripe',
        'route' => 'stripe',
        'currency' => 'USD',
        'image' => 'images/stripe.png',
        'endpoint' => 'https://api.stripe.com',
        'secret_key' => 'STRIPE_SECRET_KEY',
        'publishable_key' => 'STRIPE_PUBLISHABLE_KEY',
        'webhook_secret' => 'STRIPE_WEBHOOK_SECRET',
        'package' => [
            ['name' => '500 Silk', 'price' => 5, 'type' => 0, 'value' => 500,],
            ['name' => '1000 Silk', 'price' => 10, 'type' => 0, 'value' => 1000,],
            ['name' => '2500 Silk', 'price' => 25, 'type' => 0, 'value' => 2500,],
            ['name' => '5000 Silk', 'price' => 50, 'type' => 0, 'value' => 5000,],
            ['name' => '7500 Silk', 'price' => 75, 'type' => 0, 'value' => 7500,],
            ['name' => '10000 Silk', 'price' => 100, 'type' => 0, 'value' => 10000,],
        ],
    ],
    'nowpayments' => [
        'enabled' => false,
        'name' => 'NOWPayments',
        'route' => 'nowpayments',
        'currency' => 'USD',
        'image' => 'images/nowpayments.png',
        'endpoint' => 'https://api.nowpayments.io/v1',
        'api_key' => 'NOWPAYMENTS_API_KEY',
        'ipn_secret' => 'NOWPAYMENTS_IPN_SECRET',
        'package' => [
            ['name' => '100 Silk', 'price' => 1.00, 'type' => 0, 'value' => 100],
            ['name' => '500 Silk', 'price' => 5.00, 'type' => 0, 'value' => 500],
            ['name' => '1000 Silk', 'price' => 10.00, 'type' => 0, 'value' => 1000],
            ['name' => '2500 Silk', 'price' => 25.00, 'type' => 0, 'value' => 2500],
            ['name' => '5000 Silk', 'price' => 50.00, 'type' => 0, 'value' => 5000],
            ['name' => '7500 Silk', 'price' => 75.00, 'type' => 0, 'value' => 7500],
            ['name' => '10000 Silk', 'price' => 100.00, 'type' => 0, 'value' => 10000],
            ['name' => '25000 Silk', 'price' => 250.00, 'type' => 0, 'value' => 25000],
        ],
    ],
    'fawaterk' => [
        'enabled' => false,
        'name' => 'Fawaterk',
        'route' => 'fawaterk',
        'currency' => 'EGP',
        'image' => 'images/fawaterk.png',
        //'endpoint' => 'https://app.fawaterk.com', // for production //webhook url: http://localhost/webhook/fawaterk
        'endpoint' => 'https://staging.fawaterk.com', // for sandbox
        'api_key' => 'FAWATERK_API_KEY',
        'provider_key' => 'FAWATERK_PROVIDER_KEY',
        'package' => [
            ['name' => '500 Silk', 'price' => 5.00, 'type' => 0, 'value' => 500],
            ['name' => '1000 Silk', 'price' => 10.00, 'type' => 0, 'value' => 1000],
            ['name' => '2500 Silk', 'price' => 25.00, 'type' => 0, 'value' => 2500],
            ['name' => '5000 Silk', 'price' => 50.00, 'type' => 0, 'value' => 5000],
            ['name' => '7500 Silk', 'price' => 75.00, 'type' => 0, 'value' => 7500],
            ['name' => '10000 Silk', 'price' => 100.00, 'type' => 0, 'value' => 10000],
            ['name' => '25000 Silk', 'price' => 250.00, 'type' => 0, 'value' => 25000],
        ],
    ],
    'maxicard' => [
        'enabled' => true,
        'name' => 'MaxiCard',
        'route' => 'maxicard',
        'currency' => 'TL',
        'image' => 'images/maxicard.png',
        'endpoint' => 'https://www.maxigame.org/epin/yukle.php',
        'api_key' => 'MAXICARD_API_KEY',
        'api_password' => 'MAXICARD_API_PASSWORD',
        'package' => [
            ['name' => '100 Silk', 'price' => 1, 'type' => 0, 'value' => 100],
            ['name' => '500 Silk', 'price' => 5, 'type' => 0, 'value' => 500],
            ['name' => '1000 Silk', 'price' => 10, 'type' => 0, 'value' => 1000],
            ['name' => '2500 Silk', 'price' => 25, 'type' => 0, 'value' => 2500],
            ['name' => '5000 Silk', 'price' => 50, 'type' => 0, 'value' => 5000],
            ['name' => '7500 Silk', 'price' => 75, 'type' => 0, 'value' => 7500],
            ['name' => '10000 Silk', 'price' => 100, 'type' => 0, 'value' => 10000],
            ['name' => '25000 Silk', 'price' => 250, 'type' => 0, 'value' => 25000],
        ],
    ],
    'hipocard' => [
        'enabled' => false,
        'name' => 'HipoCard',
        'route' => 'hipocard',
        'currency' => 'TL',
        'image' => 'images/hipocard.png',
        //'endpoint' => 'https://www.hipopotamya.com/api/v1/hipocard/epins', // for production
        'endpoint' => 'https://www.hipopotamya.com/api/sandbox/v1/hipocard/epins', // for sandbox
        'api_key' => 'HIPOCARD_API_KEY',
        'api_password' => 'HIPOCARD_API_PASSWORD',
        'package' => [
            ['name' => '100 Silk', 'price' => 1.00, 'type' => 0, 'value' => 100],
            ['name' => '500 Silk', 'price' => 5.00, 'type' => 0, 'value' => 500],
            ['name' => '1000 Silk', 'price' => 10.00, 'type' => 0, 'value' => 1000],
            ['name' => '2500 Silk', 'price' => 25.00, 'type' => 0, 'value' => 2500],
            ['name' => '5000 Silk', 'price' => 50.00, 'type' => 0, 'value' => 5000],
            ['name' => '7500 Silk', 'price' => 75.00, 'type' => 0, 'value' => 7500],
            ['name' => '10000 Silk', 'price' => 100.00, 'type' => 0, 'value' => 10000],
            ['name' => '25000 Silk', 'price' => 250.00, 'type' => 0, 'value' => 25000],
        ],
    ],
    'hipopay' => [
        'enabled' => true,
        'name' => 'HipoPay',
        'route' => 'hipopay',
        'currency' => 'TL',
        'image' => 'images/hipopay.png',
        'endpoint' => 'https://www.hipopotamya.com/api/v1/merchants/payment/token', //webhook url: http://localhost/webhook/hipopay
        'api_key' => 'HIPOPAY_API_KEY',
        'api_password' => 'HIPOPAY_API_PASSWORD',
        'commission_type' => 1,
        'package' => [
            ['name' => '100 Silk', 'price' => 1, 'type' => 0, 'value' => 100],
            ['name' => '500 Silk', 'price' => 5, 'type' => 0, 'value' => 500],
            ['name' => '1000 Silk', 'price' => 10, 'type' => 0, 'value' => 1000],
            ['name' => '2500 Silk', 'price' => 25, 'type' => 0, 'value' => 2500],
            ['name' => '5000 Silk', 'price' => 50, 'type' => 0, 'value' => 5000],
            ['name' => '7500 Silk', 'price' => 75, 'type' => 0, 'value' => 7500],
            ['name' => '10000 Silk', 'price' => 100, 'type' => 0, 'value' => 10000],
            ['name' => '25000 Silk', 'price' => 250, 'type' => 0, 'value' => 25000],
        ],
    ],
    'custom' => [
        'enabled' => false,
        'name' => 'Custom Donate',
        'route' => 'custom',
        'currency' => 'USD',
        'image' => 'images/custom.png',
        'html' => '',
        'package' => [],
    ],
];
