<?php

return [
    594 => ['name' => 'MATTR_SELF_PARTY_DAMAGE_ABS_INC_TITLE', 'desc' => 'MATTR_SELF_PARTY_DAMAGE_ABS_INC_TITLE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    593 => ['name' => 'MATTR_SELF_PARTY_HWAN_REGEN_TITLE', 'desc' => 'MATTR_SELF_PARTY_HWAN_REGEN_TITLE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    592 => ['name' => 'MATTR_SHARE_PARTY_DAMAGE_ABS_INC_TITLE', 'desc' => 'MATTR_SHARE_PARTY_DAMAGE_ABS_INC_TITLE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    591 => ['name' => 'MATTR_SHARE_PARTY_HWAN_REGEN_TITLE', 'desc' => 'MATTR_SHARE_PARTY_HWAN_REGEN_TITLE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    590 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    589 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    588 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    587 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    586 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'MATTR_REGENHPMP', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    585 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    584 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    583 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    582 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 15, 'extension' => '', 'sortkey' => 7],
    581 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 15, 'extension' => '', 'sortkey' => 6],
    580 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 15, 'extension' => '', 'sortkey' => 4],
    579 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 15, 'extension' => '', 'sortkey' => 5],
    578 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 15, 'extension' => '', 'sortkey' => 3],
    577 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 15, 'extension' => '', 'sortkey' => 9],
    576 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 15, 'extension' => '', 'sortkey' => 8],
    575 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 15, 'extension' => '', 'sortkey' => 7],
    574 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 15, 'extension' => '', 'sortkey' => 7],
    573 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 15, 'extension' => '', 'sortkey' => 8],
    572 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 15, 'extension' => '', 'sortkey' => 7],
    571 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 15, 'extension' => '', 'sortkey' => 6],
    570 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    569 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 15, 'extension' => '', 'sortkey' => 0],
    568 => ['name' => 'MATTR_INC_MV_SPEED_R', 'desc' => 'MATTR_INC_MV_SPEED_R', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    567 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    566 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    565 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    564 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    563 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'MATTR_REGENHPMP', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    562 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    561 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    560 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    559 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 14, 'extension' => '', 'sortkey' => 7],
    558 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 14, 'extension' => '', 'sortkey' => 6],
    557 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 14, 'extension' => '', 'sortkey' => 4],
    556 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 14, 'extension' => '', 'sortkey' => 5],
    555 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 14, 'extension' => '', 'sortkey' => 3],
    554 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 14, 'extension' => '', 'sortkey' => 9],
    553 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 14, 'extension' => '', 'sortkey' => 8],
    552 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 14, 'extension' => '', 'sortkey' => 7],
    551 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 14, 'extension' => '', 'sortkey' => 7],
    550 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 14, 'extension' => '', 'sortkey' => 8],
    549 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 14, 'extension' => '', 'sortkey' => 7],
    548 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 14, 'extension' => '', 'sortkey' => 6],
    547 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    546 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 14, 'extension' => '', 'sortkey' => 0],
    545 => ['name' => 'MATTR_SELF_PARTY_DAMAGE_UP_TITLE', 'desc' => 'MATTR_SELF_PARTY_DAMAGE_UP_TITLE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    544 => ['name' => 'MATTR_SHARE_PARTY_DAMAGE_UP_TITLE', 'desc' => 'MATTR_SHARE_PARTY_DAMAGE_UP_TITLE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    543 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    542 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    541 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    540 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    539 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'MATTR_REGENHPMP', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    538 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    537 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    536 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    535 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 13, 'extension' => '', 'sortkey' => 7],
    534 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 13, 'extension' => '', 'sortkey' => 6],
    533 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 13, 'extension' => '', 'sortkey' => 4],
    532 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 13, 'extension' => '', 'sortkey' => 5],
    531 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 13, 'extension' => '', 'sortkey' => 3],
    530 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 13, 'extension' => '', 'sortkey' => 9],
    529 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 13, 'extension' => '', 'sortkey' => 8],
    528 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 13, 'extension' => '', 'sortkey' => 7],
    527 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 13, 'extension' => '', 'sortkey' => 7],
    526 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 13, 'extension' => '', 'sortkey' => 8],
    525 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 13, 'extension' => '', 'sortkey' => 7],
    524 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 13, 'extension' => '', 'sortkey' => 6],
    523 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    522 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 13, 'extension' => '', 'sortkey' => 0],
    521 => ['name' => 'MATTR_PET_RESIST_FEAR', 'desc' => 'MATTR_PET_RESIST_FEAR', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    520 => ['name' => 'MATTR_PET_RESIST_FEAR', 'desc' => 'MATTR_PET_RESIST_FEAR', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    519 => ['name' => 'MATTR_PET_RESIST_FEAR', 'desc' => 'MATTR_PET_RESIST_FEAR', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    518 => ['name' => 'MATTR_PET_RESIST_FEAR', 'desc' => 'MATTR_PET_RESIST_FEAR', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    517 => ['name' => 'MATTR_PET_RESIST_FEAR', 'desc' => 'MATTR_PET_RESIST_FEAR', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    516 => ['name' => 'MATTR_PET_RESIST_SLEEP', 'desc' => 'MATTR_PET_RESIST_SLEEP', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    515 => ['name' => 'MATTR_PET_RESIST_SLEEP', 'desc' => 'MATTR_PET_RESIST_SLEEP', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    514 => ['name' => 'MATTR_PET_RESIST_SLEEP', 'desc' => 'MATTR_PET_RESIST_SLEEP', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    513 => ['name' => 'MATTR_PET_RESIST_SLEEP', 'desc' => 'MATTR_PET_RESIST_SLEEP', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    512 => ['name' => 'MATTR_PET_RESIST_SLEEP', 'desc' => 'MATTR_PET_RESIST_SLEEP', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    511 => ['name' => 'MATTR_PET_RESIST_DISEASE', 'desc' => 'MATTR_PET_RESIST_DISEASE', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    510 => ['name' => 'MATTR_PET_RESIST_DISEASE', 'desc' => 'MATTR_PET_RESIST_DISEASE', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    509 => ['name' => 'MATTR_PET_RESIST_DISEASE', 'desc' => 'MATTR_PET_RESIST_DISEASE', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    508 => ['name' => 'MATTR_PET_RESIST_DISEASE', 'desc' => 'MATTR_PET_RESIST_DISEASE', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    507 => ['name' => 'MATTR_PET_RESIST_DISEASE', 'desc' => 'MATTR_PET_RESIST_DISEASE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    506 => ['name' => 'MATTR_PET_RESIST_CSMP', 'desc' => 'MATTR_PET_RESIST_CSMP', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    505 => ['name' => 'MATTR_PET_RESIST_CSMP', 'desc' => 'MATTR_PET_RESIST_CSMP', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    504 => ['name' => 'MATTR_PET_RESIST_CSMP', 'desc' => 'MATTR_PET_RESIST_CSMP', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    503 => ['name' => 'MATTR_PET_RESIST_CSMP', 'desc' => 'MATTR_PET_RESIST_CSMP', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    502 => ['name' => 'MATTR_PET_RESIST_CSMP', 'desc' => 'MATTR_PET_RESIST_CSMP', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    501 => ['name' => 'MATTR_PET_RESIST_STUN', 'desc' => 'MATTR_PET_RESIST_STUN', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    500 => ['name' => 'MATTR_PET_RESIST_STUN', 'desc' => 'MATTR_PET_RESIST_STUN', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    499 => ['name' => 'MATTR_PET_RESIST_STUN', 'desc' => 'MATTR_PET_RESIST_STUN', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    498 => ['name' => 'MATTR_PET_RESIST_STUN', 'desc' => 'MATTR_PET_RESIST_STUN', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    497 => ['name' => 'MATTR_PET_RESIST_STUN', 'desc' => 'MATTR_PET_RESIST_STUN', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    496 => ['name' => 'MATTR_PET_RESIST_ZOMBIE', 'desc' => 'MATTR_PET_RESIST_ZOMBIE', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    495 => ['name' => 'MATTR_PET_RESIST_ZOMBIE', 'desc' => 'MATTR_PET_RESIST_ZOMBIE', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    494 => ['name' => 'MATTR_PET_RESIST_ZOMBIE', 'desc' => 'MATTR_PET_RESIST_ZOMBIE', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    493 => ['name' => 'MATTR_PET_RESIST_ZOMBIE', 'desc' => 'MATTR_PET_RESIST_ZOMBIE', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    492 => ['name' => 'MATTR_PET_RESIST_ZOMBIE', 'desc' => 'MATTR_PET_RESIST_ZOMBIE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    491 => ['name' => 'MATTR_PET_RESIST_POISON', 'desc' => 'MATTR_PET_RESIST_POISON', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    490 => ['name' => 'MATTR_PET_RESIST_POISON', 'desc' => 'MATTR_PET_RESIST_POISON', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    489 => ['name' => 'MATTR_PET_RESIST_POISON', 'desc' => 'MATTR_PET_RESIST_POISON', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    488 => ['name' => 'MATTR_PET_RESIST_POISON', 'desc' => 'MATTR_PET_RESIST_POISON', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    487 => ['name' => 'MATTR_PET_RESIST_POISON', 'desc' => 'MATTR_PET_RESIST_POISON', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    486 => ['name' => 'MATTR_PET_RESIST_BURN', 'desc' => 'MATTR_PET_RESIST_BURN', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    485 => ['name' => 'MATTR_PET_RESIST_BURN', 'desc' => 'MATTR_PET_RESIST_BURN', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    484 => ['name' => 'MATTR_PET_RESIST_BURN', 'desc' => 'MATTR_PET_RESIST_BURN', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    483 => ['name' => 'MATTR_PET_RESIST_BURN', 'desc' => 'MATTR_PET_RESIST_BURN', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    482 => ['name' => 'MATTR_PET_RESIST_BURN', 'desc' => 'MATTR_PET_RESIST_BURN', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    481 => ['name' => 'MATTR_PET_RESIST_ESHOCK', 'desc' => 'MATTR_PET_RESIST_ESHOCK', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    480 => ['name' => 'MATTR_PET_RESIST_ESHOCK', 'desc' => 'MATTR_PET_RESIST_ESHOCK', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    479 => ['name' => 'MATTR_PET_RESIST_ESHOCK', 'desc' => 'MATTR_PET_RESIST_ESHOCK', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    478 => ['name' => 'MATTR_PET_RESIST_ESHOCK', 'desc' => 'MATTR_PET_RESIST_ESHOCK', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    477 => ['name' => 'MATTR_PET_RESIST_ESHOCK', 'desc' => 'MATTR_PET_RESIST_ESHOCK', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    476 => ['name' => 'MATTR_PET_RESIST_FROSTBITE', 'desc' => 'MATTR_PET_RESIST_FROSTBITE', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    475 => ['name' => 'MATTR_PET_RESIST_FROSTBITE', 'desc' => 'MATTR_PET_RESIST_FROSTBITE', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    474 => ['name' => 'MATTR_PET_RESIST_FROSTBITE', 'desc' => 'MATTR_PET_RESIST_FROSTBITE', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    473 => ['name' => 'MATTR_PET_RESIST_FROSTBITE', 'desc' => 'MATTR_PET_RESIST_FROSTBITE', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    472 => ['name' => 'MATTR_PET_RESIST_FROSTBITE', 'desc' => 'MATTR_PET_RESIST_FROSTBITE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    471 => ['name' => 'MATTR_PET_REGENHPMP', 'desc' => 'MATTR_PET_REGENHPMP', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    470 => ['name' => 'MATTR_PET_REGENHPMP', 'desc' => 'MATTR_PET_REGENHPMP', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    469 => ['name' => 'MATTR_PET_REGENHPMP', 'desc' => 'MATTR_PET_REGENHPMP', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    468 => ['name' => 'MATTR_PET_REGENHPMP', 'desc' => 'MATTR_PET_REGENHPMP', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    467 => ['name' => 'MATTR_PET_REGENHPMP', 'desc' => 'MATTR_PET_REGENHPMP', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    466 => ['name' => 'MATTR_PET_HP', 'desc' => 'MATTR_PET_HP', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    465 => ['name' => 'MATTR_PET_HP', 'desc' => 'MATTR_PET_HP', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    464 => ['name' => 'MATTR_PET_HP', 'desc' => 'MATTR_PET_HP', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    463 => ['name' => 'MATTR_PET_HP', 'desc' => 'MATTR_PET_HP', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    462 => ['name' => 'MATTR_PET_HP', 'desc' => 'MATTR_PET_HP', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    461 => ['name' => 'MATTR_PET_ER', 'desc' => 'MATTR_PET_ER', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    460 => ['name' => 'MATTR_PET_ER', 'desc' => 'MATTR_PET_ER', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    459 => ['name' => 'MATTR_PET_ER', 'desc' => 'MATTR_PET_ER', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    458 => ['name' => 'MATTR_PET_ER', 'desc' => 'MATTR_PET_ER', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    457 => ['name' => 'MATTR_PET_ER', 'desc' => 'MATTR_PET_ER', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    456 => ['name' => 'MATTR_PET_CRITICAL', 'desc' => 'MATTR_PET_CRITICAL', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    455 => ['name' => 'MATTR_PET_CRITICAL', 'desc' => 'MATTR_PET_CRITICAL', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    454 => ['name' => 'MATTR_PET_CRITICAL', 'desc' => 'MATTR_PET_CRITICAL', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    453 => ['name' => 'MATTR_PET_CRITICAL', 'desc' => 'MATTR_PET_CRITICAL', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    452 => ['name' => 'MATTR_PET_CRITICAL', 'desc' => 'MATTR_PET_CRITICAL', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    451 => ['name' => 'MATTR_PET_EVADE_BLOCK', 'desc' => 'MATTR_PET_EVADE_BLOCK', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    450 => ['name' => 'MATTR_PET_EVADE_BLOCK', 'desc' => 'MATTR_PET_EVADE_BLOCK', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    449 => ['name' => 'MATTR_PET_EVADE_BLOCK', 'desc' => 'MATTR_PET_EVADE_BLOCK', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    448 => ['name' => 'MATTR_PET_EVADE_BLOCK', 'desc' => 'MATTR_PET_EVADE_BLOCK', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    447 => ['name' => 'MATTR_PET_EVADE_BLOCK', 'desc' => 'MATTR_PET_EVADE_BLOCK', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    446 => ['name' => 'MATTR_PET_HR', 'desc' => 'MATTR_PET_HR', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    445 => ['name' => 'MATTR_PET_HR', 'desc' => 'MATTR_PET_HR', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    444 => ['name' => 'MATTR_PET_HR', 'desc' => 'MATTR_PET_HR', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    443 => ['name' => 'MATTR_PET_HR', 'desc' => 'MATTR_PET_HR', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    442 => ['name' => 'MATTR_PET_HR', 'desc' => 'MATTR_PET_HR', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    441 => ['name' => 'MATTR_PET_BLOCKRATE', 'desc' => 'MATTR_PET_BLOCKRATE', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    440 => ['name' => 'MATTR_PET_BLOCKRATE', 'desc' => 'MATTR_PET_BLOCKRATE', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    439 => ['name' => 'MATTR_PET_BLOCKRATE', 'desc' => 'MATTR_PET_BLOCKRATE', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    438 => ['name' => 'MATTR_PET_BLOCKRATE', 'desc' => 'MATTR_PET_BLOCKRATE', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    437 => ['name' => 'MATTR_PET_BLOCKRATE', 'desc' => 'MATTR_PET_BLOCKRATE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    436 => ['name' => 'MATTR_PET_EVADE_CRITICAL', 'desc' => 'MATTR_PET_EVADE_CRITICAL', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    435 => ['name' => 'MATTR_PET_EVADE_CRITICAL', 'desc' => 'MATTR_PET_EVADE_CRITICAL', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    434 => ['name' => 'MATTR_PET_EVADE_CRITICAL', 'desc' => 'MATTR_PET_EVADE_CRITICAL', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    433 => ['name' => 'MATTR_PET_EVADE_CRITICAL', 'desc' => 'MATTR_PET_EVADE_CRITICAL', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    432 => ['name' => 'MATTR_PET_EVADE_CRITICAL', 'desc' => 'MATTR_PET_EVADE_CRITICAL', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    431 => ['name' => 'MATTR_PET_INT', 'desc' => 'MATTR_PET_INT', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    430 => ['name' => 'MATTR_PET_INT', 'desc' => 'MATTR_PET_INT', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    429 => ['name' => 'MATTR_PET_INT', 'desc' => 'MATTR_PET_INT', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    428 => ['name' => 'MATTR_PET_INT', 'desc' => 'MATTR_PET_INT', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    427 => ['name' => 'MATTR_PET_INT', 'desc' => 'MATTR_PET_INT', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    426 => ['name' => 'MATTR_PET_STR', 'desc' => 'MATTR_PET_STR', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    425 => ['name' => 'MATTR_PET_STR', 'desc' => 'MATTR_PET_STR', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    424 => ['name' => 'MATTR_PET_STR', 'desc' => 'MATTR_PET_STR', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    423 => ['name' => 'MATTR_PET_STR', 'desc' => 'MATTR_PET_STR', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    422 => ['name' => 'MATTR_PET_STR', 'desc' => 'MATTR_PET_STR', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    421 => ['name' => 'MATTR_PET_DUR', 'desc' => 'MATTR_PET_DUR', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    420 => ['name' => 'MATTR_PET_DUR', 'desc' => 'MATTR_PET_DUR', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    419 => ['name' => 'MATTR_PET_DUR', 'desc' => 'MATTR_PET_DUR', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    418 => ['name' => 'MATTR_PET_DUR', 'desc' => 'MATTR_PET_DUR', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    417 => ['name' => 'MATTR_PET_DUR', 'desc' => 'MATTR_PET_DUR', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    416 => ['name' => 'MATTR_TRADE_MP_3', 'desc' => 'MP %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    415 => ['name' => 'MATTR_TRADE_MP_3', 'desc' => 'MP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    414 => ['name' => 'MATTR_TRADE_MP_2', 'desc' => 'MP %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    413 => ['name' => 'MATTR_TRADE_MP_2', 'desc' => 'MP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    412 => ['name' => 'MATTR_TRADE_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    411 => ['name' => 'MATTR_TRADE_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    410 => ['name' => 'MATTR_TRADE_HP_3', 'desc' => 'HP %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    409 => ['name' => 'MATTR_TRADE_HP_3', 'desc' => 'HP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    408 => ['name' => 'MATTR_TRADE_HP_2', 'desc' => 'HP %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    407 => ['name' => 'MATTR_TRADE_HP_2', 'desc' => 'HP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    406 => ['name' => 'MATTR_TRADE_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    405 => ['name' => 'MATTR_TRADE_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    404 => ['name' => 'MATTR_TRADE_INT_3', 'desc' => 'Int %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    403 => ['name' => 'MATTR_TRADE_INT_3', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    402 => ['name' => 'MATTR_TRADE_INT_2', 'desc' => 'Int %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    401 => ['name' => 'MATTR_TRADE_INT_2', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    400 => ['name' => 'MATTR_TRADE_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    399 => ['name' => 'MATTR_TRADE_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    398 => ['name' => 'MATTR_TRADE_STR_3', 'desc' => 'Str %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    397 => ['name' => 'MATTR_TRADE_STR_3', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    396 => ['name' => 'MATTR_TRADE_STR_2', 'desc' => 'Str %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    395 => ['name' => 'MATTR_TRADE_STR_2', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    394 => ['name' => 'MATTR_TRADE_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    393 => ['name' => 'MATTR_TRADE_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    392 => ['name' => 'MATTR_INT_AVATAR', 'desc' => 'Int %desc% Increase', 'mLevel' => 5, 'extension' => '', 'sortkey' => 2],
    391 => ['name' => 'MATTR_STR_AVATAR', 'desc' => 'Str %desc% Increase', 'mLevel' => 5, 'extension' => '', 'sortkey' => 1],
    390 => ['name' => 'MATTR_RESIST_ALL_SET', 'desc' => 'MATTR_RESIST_ALL_SET', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    389 => ['name' => 'MATTR_REINFORCE_ITEM_SET', 'desc' => 'MATTR_REINFORCE_ITEM_SET', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    388 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    387 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    386 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    385 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    384 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    383 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    382 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    381 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    380 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    379 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    378 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    377 => ['name' => 'MATTR_APE', 'desc' => 'MATTR_APE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    376 => ['name' => 'MATTR_AVATAR_LUCK_4', 'desc' => 'Luck %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 12],
    375 => ['name' => 'MATTR_AVATAR_LUCK_3', 'desc' => 'Luck %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 11],
    374 => ['name' => 'MATTR_AVATAR_LUCK_2', 'desc' => 'Luck %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 10],
    373 => ['name' => 'MATTR_AVATAR_LUCK', 'desc' => 'Luck %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 9],
    372 => ['name' => 'MATTR_AVATAR_MDIA_4', 'desc' => 'Ignore Monster Defense %desc% Proability', 'mLevel' => 1, 'extension' => '', 'sortkey' => 16],
    371 => ['name' => 'MATTR_AVATAR_MDIA_3', 'desc' => 'Ignore Monster Defense %desc% Proability', 'mLevel' => 1, 'extension' => '', 'sortkey' => 15],
    370 => ['name' => 'MATTR_AVATAR_MDIA_2', 'desc' => 'Ignore Monster Defense %desc% Proability', 'mLevel' => 1, 'extension' => '', 'sortkey' => 14],
    369 => ['name' => 'MATTR_AVATAR_INT_4', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 8],
    368 => ['name' => 'MATTR_AVATAR_INT_3', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 7],
    367 => ['name' => 'MATTR_AVATAR_INT_2', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 6],
    366 => ['name' => 'MATTR_AVATAR_STR_4', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 4],
    365 => ['name' => 'MATTR_AVATAR_STR_3', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 3],
    364 => ['name' => 'MATTR_AVATAR_STR_2', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 2],
    363 => ['name' => 'MATTR_LUCK_SET', 'desc' => 'Luck %desc% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    362 => ['name' => 'MATTR_DUR_SET', 'desc' => 'MATTR_DUR_SET', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    361 => ['name' => 'MATTR_MP_SET', 'desc' => 'MATTR_MP_SET', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    360 => ['name' => 'MATTR_HP_SET', 'desc' => 'MATTR_HP_SET', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    359 => ['name' => 'MATTR_ER_SET', 'desc' => 'MATTR_ER_SET', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    358 => ['name' => 'MATTR_INT_SET', 'desc' => 'Int %desc% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    357 => ['name' => 'MATTR_STR_SET', 'desc' => 'Str %desc% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    356 => ['name' => 'MATTR_NASRUN_BLOCKRATE', 'desc' => 'MATTR_NASRUN_BLOCKRATE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 4],
    355 => ['name' => 'MATTR_NASRUN_MPNA', 'desc' => 'MATTR_NASRUN_MPNA', 'mLevel' => 1, 'extension' => '', 'sortkey' => 2],
    354 => ['name' => 'MATTR_NASRUN_HPNA', 'desc' => 'MATTR_NASRUN_HPNA', 'mLevel' => 1, 'extension' => '', 'sortkey' => 1],
    353 => ['name' => 'MATTR_NASRUN_UMDU', 'desc' => '%desc% Damage increase (it will apply to Unique monster only)', 'mLevel' => 1, 'extension' => '', 'sortkey' => 3],
    352 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    351 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    350 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    349 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    348 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    347 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    346 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    345 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    344 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    343 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    342 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    341 => ['name' => 'MATTR_RESIST_FEAR', 'desc' => 'MATTR_RESIST_FEAR', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    340 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    339 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    338 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    337 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    336 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    335 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    334 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    333 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    332 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    331 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    330 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    329 => ['name' => 'MATTR_RESIST_SLEEP', 'desc' => 'MATTR_RESIST_SLEEP', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    328 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    327 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    326 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    325 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    324 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    323 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    322 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    321 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    320 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    319 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    318 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    317 => ['name' => 'MATTR_RESIST_DISEASE', 'desc' => 'MATTR_RESIST_DISEASE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    316 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    315 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    314 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    313 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    312 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    311 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    310 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    309 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    308 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    307 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    306 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    305 => ['name' => 'MATTR_RESIST_CSMP', 'desc' => 'MATTR_RESIST_CSMP', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    304 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    303 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    302 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    301 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    300 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    299 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    298 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    297 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    296 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    295 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    294 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    293 => ['name' => 'MATTR_REGENHPMP', 'desc' => 'HP recovery/MP recovery %desc%', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    292 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    291 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    290 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    289 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    288 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    287 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    286 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    285 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    284 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    283 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    282 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    281 => ['name' => 'MATTR_RESIST_STUN', 'desc' => 'StunProbaility %desc%% Reduce', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    280 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    279 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    278 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    277 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    276 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    275 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    274 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    273 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    272 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    271 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    270 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    269 => ['name' => 'MATTR_BLOCKRATE', 'desc' => 'Blocking rate %desc%', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    268 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    267 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    266 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    265 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    264 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    263 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    262 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    261 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    260 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    259 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    258 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    257 => ['name' => 'MATTR_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    256 => ['name' => 'MATTR_AVATAR_MPRG', 'desc' => 'MP Recovery %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 6],
    255 => ['name' => 'MATTR_AVATAR_HPRG', 'desc' => 'HP Recovery %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 20],
    254 => ['name' => 'MATTR_AVATAR_MDIA', 'desc' => 'Ignore Monster Defense %desc% Proability', 'mLevel' => 1, 'extension' => '', 'sortkey' => 13],
    253 => ['name' => 'MATTR_AVATAR_DARA', 'desc' => 'Damage Absorption %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 5],
    252 => ['name' => 'MATTR_AVATAR_DRUA', 'desc' => 'Damage %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 19],
    251 => ['name' => 'MATTR_AVATAR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 4],
    250 => ['name' => 'MATTR_AVATAR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 18],
    249 => ['name' => 'MATTR_AVATAR_ER', 'desc' => 'Parry rate %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 3],
    248 => ['name' => 'MATTR_AVATAR_HR', 'desc' => 'Attack rate %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 17],
    247 => ['name' => 'MATTR_AVATAR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 5],
    246 => ['name' => 'MATTR_AVATAR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 1],
    245 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 12, 'extension' => '', 'sortkey' => 9],
    244 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 11, 'extension' => '', 'sortkey' => 9],
    243 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 10, 'extension' => '', 'sortkey' => 9],
    242 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 9, 'extension' => '', 'sortkey' => 9],
    241 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 8, 'extension' => '', 'sortkey' => 9],
    240 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 7, 'extension' => '', 'sortkey' => 9],
    239 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 6, 'extension' => '', 'sortkey' => 9],
    238 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 5, 'extension' => '', 'sortkey' => 9],
    237 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 4, 'extension' => '', 'sortkey' => 9],
    236 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 3, 'extension' => '', 'sortkey' => 9],
    235 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 2, 'extension' => '', 'sortkey' => 9],
    234 => ['name' => 'MATTR_REPAIR', 'desc' => 'Available Number of Repair (%desc% Time/times)', 'mLevel' => 1, 'extension' => '', 'sortkey' => 9],
    233 => ['name' => 'MATTR_INT_AVATAR', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 2],
    232 => ['name' => 'MATTR_STR_AVATAR', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 1],
    231 => ['name' => 'MATTR_INT_3JOB', 'desc' => 'Int %desc% Increase', 'mLevel' => 4, 'extension' => '', 'sortkey' => 2],
    230 => ['name' => 'MATTR_INT_3JOB', 'desc' => 'Int %desc% Increase', 'mLevel' => 3, 'extension' => '', 'sortkey' => 2],
    229 => ['name' => 'MATTR_INT_3JOB', 'desc' => 'Int %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 2],
    228 => ['name' => 'MATTR_INT_3JOB', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 2],
    227 => ['name' => 'MATTR_STR_3JOB', 'desc' => 'Str %desc% Increase', 'mLevel' => 4, 'extension' => '', 'sortkey' => 1],
    226 => ['name' => 'MATTR_STR_3JOB', 'desc' => 'Str %desc% Increase', 'mLevel' => 3, 'extension' => '', 'sortkey' => 1],
    225 => ['name' => 'MATTR_STR_3JOB', 'desc' => 'Str %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 1],
    224 => ['name' => 'MATTR_STR_3JOB', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 1],
    223 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 12, 'extension' => '', 'sortkey' => 0],
    222 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 11, 'extension' => '', 'sortkey' => 0],
    221 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 10, 'extension' => '', 'sortkey' => 0],
    220 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 9, 'extension' => '', 'sortkey' => 0],
    219 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 8, 'extension' => '', 'sortkey' => 0],
    218 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 7, 'extension' => '', 'sortkey' => 0],
    217 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 6, 'extension' => '', 'sortkey' => 0],
    216 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 5, 'extension' => '', 'sortkey' => 0],
    215 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    214 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    213 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    212 => ['name' => 'MATTR_ASTRAL', 'desc' => 'Astral (%desc% Time/times)', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    211 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 12, 'extension' => '', 'sortkey' => 9],
    210 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 11, 'extension' => '', 'sortkey' => 9],
    209 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 10, 'extension' => '', 'sortkey' => 9],
    208 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 9, 'extension' => '', 'sortkey' => 9],
    207 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 8, 'extension' => '', 'sortkey' => 9],
    206 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 7, 'extension' => '', 'sortkey' => 9],
    205 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 12, 'extension' => '', 'sortkey' => 4],
    204 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 11, 'extension' => '', 'sortkey' => 4],
    203 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 10, 'extension' => '', 'sortkey' => 4],
    202 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 9, 'extension' => '', 'sortkey' => 4],
    201 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 8, 'extension' => '', 'sortkey' => 4],
    200 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 7, 'extension' => '', 'sortkey' => 4],
    199 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 12, 'extension' => '', 'sortkey' => 8],
    198 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 11, 'extension' => '', 'sortkey' => 8],
    197 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 10, 'extension' => '', 'sortkey' => 8],
    196 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 9, 'extension' => '', 'sortkey' => 8],
    195 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 8, 'extension' => '', 'sortkey' => 8],
    194 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 7, 'extension' => '', 'sortkey' => 8],
    193 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 12, 'extension' => '', 'sortkey' => 7],
    192 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 11, 'extension' => '', 'sortkey' => 7],
    191 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 10, 'extension' => '', 'sortkey' => 7],
    190 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 9, 'extension' => '', 'sortkey' => 7],
    189 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 8, 'extension' => '', 'sortkey' => 7],
    188 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 7, 'extension' => '', 'sortkey' => 7],
    187 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 12, 'extension' => '', 'sortkey' => 6],
    186 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 11, 'extension' => '', 'sortkey' => 6],
    185 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 10, 'extension' => '', 'sortkey' => 6],
    184 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 9, 'extension' => '', 'sortkey' => 6],
    183 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 8, 'extension' => '', 'sortkey' => 6],
    182 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 7, 'extension' => '', 'sortkey' => 6],
    181 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 12, 'extension' => '', 'sortkey' => 4],
    180 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 11, 'extension' => '', 'sortkey' => 4],
    179 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 10, 'extension' => '', 'sortkey' => 4],
    178 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 9, 'extension' => '', 'sortkey' => 4],
    177 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 8, 'extension' => '', 'sortkey' => 4],
    176 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 7, 'extension' => '', 'sortkey' => 4],
    175 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 12, 'extension' => '', 'sortkey' => 5],
    174 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 11, 'extension' => '', 'sortkey' => 5],
    173 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 10, 'extension' => '', 'sortkey' => 5],
    172 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 9, 'extension' => '', 'sortkey' => 5],
    171 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 8, 'extension' => '', 'sortkey' => 5],
    170 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 7, 'extension' => '', 'sortkey' => 5],
    169 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 12, 'extension' => '', 'sortkey' => 3],
    168 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 11, 'extension' => '', 'sortkey' => 3],
    167 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 10, 'extension' => '', 'sortkey' => 3],
    166 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 9, 'extension' => '', 'sortkey' => 3],
    165 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 8, 'extension' => '', 'sortkey' => 3],
    164 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 7, 'extension' => '', 'sortkey' => 3],
    163 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 12, 'extension' => '', 'sortkey' => 9],
    162 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 11, 'extension' => '', 'sortkey' => 9],
    161 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 9],
    160 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 9, 'extension' => '', 'sortkey' => 9],
    159 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 8, 'extension' => '', 'sortkey' => 9],
    158 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 7, 'extension' => '', 'sortkey' => 9],
    157 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 6, 'extension' => '', 'sortkey' => 9],
    156 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 5, 'extension' => '', 'sortkey' => 9],
    155 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 4, 'extension' => '', 'sortkey' => 9],
    154 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 3, 'extension' => '', 'sortkey' => 9],
    153 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 9],
    152 => ['name' => 'MATTR_MP', 'desc' => 'MP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 9],
    151 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 12, 'extension' => '', 'sortkey' => 8],
    150 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 11, 'extension' => '', 'sortkey' => 8],
    149 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 8],
    148 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 9, 'extension' => '', 'sortkey' => 8],
    147 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 8, 'extension' => '', 'sortkey' => 8],
    146 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 7, 'extension' => '', 'sortkey' => 8],
    145 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 6, 'extension' => '', 'sortkey' => 8],
    144 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 5, 'extension' => '', 'sortkey' => 8],
    143 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 4, 'extension' => '', 'sortkey' => 8],
    142 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 3, 'extension' => '', 'sortkey' => 8],
    141 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 8],
    140 => ['name' => 'MATTR_HP', 'desc' => 'HP %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 8],
    139 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 12, 'extension' => '', 'sortkey' => 7],
    138 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 11, 'extension' => '', 'sortkey' => 7],
    137 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 7],
    136 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 9, 'extension' => '', 'sortkey' => 7],
    135 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 8, 'extension' => '', 'sortkey' => 7],
    134 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 7, 'extension' => '', 'sortkey' => 7],
    133 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 6, 'extension' => '', 'sortkey' => 7],
    132 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 5, 'extension' => '', 'sortkey' => 7],
    131 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 4, 'extension' => '', 'sortkey' => 7],
    130 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 3, 'extension' => '', 'sortkey' => 7],
    129 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 7],
    128 => ['name' => 'MATTR_ER', 'desc' => 'Parry rate %desc%% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 7],
    127 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 12, 'extension' => '', 'sortkey' => 7],
    126 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 11, 'extension' => '', 'sortkey' => 7],
    125 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 10, 'extension' => '', 'sortkey' => 7],
    124 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 9, 'extension' => '', 'sortkey' => 7],
    123 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 8, 'extension' => '', 'sortkey' => 7],
    122 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 7, 'extension' => '', 'sortkey' => 7],
    121 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 6, 'extension' => '', 'sortkey' => 7],
    120 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 5, 'extension' => '', 'sortkey' => 7],
    119 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 4, 'extension' => '', 'sortkey' => 7],
    118 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 3, 'extension' => '', 'sortkey' => 7],
    117 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 2, 'extension' => '', 'sortkey' => 7],
    116 => ['name' => 'MATTR_EVADE_CRITICAL', 'desc' => 'Critical %desc%', 'mLevel' => 1, 'extension' => '', 'sortkey' => 7],
    115 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 12, 'extension' => '', 'sortkey' => 8],
    114 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 11, 'extension' => '', 'sortkey' => 8],
    113 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 10, 'extension' => '', 'sortkey' => 8],
    112 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 9, 'extension' => '', 'sortkey' => 8],
    111 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 8, 'extension' => '', 'sortkey' => 8],
    110 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 7, 'extension' => '', 'sortkey' => 8],
    109 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 6, 'extension' => '', 'sortkey' => 8],
    108 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 5, 'extension' => '', 'sortkey' => 8],
    107 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 4, 'extension' => '', 'sortkey' => 8],
    106 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 3, 'extension' => '', 'sortkey' => 8],
    105 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 2, 'extension' => '', 'sortkey' => 8],
    104 => ['name' => 'MATTR_EVADE_BLOCK', 'desc' => 'Blocking ratio %desc%', 'mLevel' => 1, 'extension' => '', 'sortkey' => 8],
    103 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 12, 'extension' => '', 'sortkey' => 7],
    102 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 11, 'extension' => '', 'sortkey' => 7],
    101 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 7],
    100 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 9, 'extension' => '', 'sortkey' => 7],
    99 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 8, 'extension' => '', 'sortkey' => 7],
    98 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 7, 'extension' => '', 'sortkey' => 7],
    97 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 6, 'extension' => '', 'sortkey' => 7],
    96 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 5, 'extension' => '', 'sortkey' => 7],
    95 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 4, 'extension' => '', 'sortkey' => 7],
    94 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 3, 'extension' => '', 'sortkey' => 7],
    93 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 7],
    92 => ['name' => 'MATTR_HR', 'desc' => 'Attack rate %desc%% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 7],
    91 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 12, 'extension' => '', 'sortkey' => 6],
    90 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 11, 'extension' => '', 'sortkey' => 6],
    89 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 6],
    88 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 9, 'extension' => '', 'sortkey' => 6],
    87 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 8, 'extension' => '', 'sortkey' => 6],
    86 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 7, 'extension' => '', 'sortkey' => 6],
    85 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 6, 'extension' => '', 'sortkey' => 6],
    84 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 5, 'extension' => '', 'sortkey' => 6],
    83 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 4, 'extension' => '', 'sortkey' => 6],
    82 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 3, 'extension' => '', 'sortkey' => 6],
    81 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 6],
    80 => ['name' => 'MATTR_DUR', 'desc' => 'Durability %desc%% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 6],
    79 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 12, 'extension' => '', 'sortkey' => 2],
    78 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 11, 'extension' => '', 'sortkey' => 2],
    77 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 2],
    76 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 9, 'extension' => '', 'sortkey' => 2],
    75 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 8, 'extension' => '', 'sortkey' => 2],
    74 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 7, 'extension' => '', 'sortkey' => 2],
    73 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 12, 'extension' => '', 'sortkey' => 1],
    72 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 11, 'extension' => '', 'sortkey' => 1],
    71 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 10, 'extension' => '', 'sortkey' => 1],
    70 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 9, 'extension' => '', 'sortkey' => 1],
    69 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 8, 'extension' => '', 'sortkey' => 1],
    68 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 7, 'extension' => '', 'sortkey' => 1],
    67 => ['name' => 'MATTR_REINFORCE_ITEM', 'desc' => 'MATTR_REINFORCE_ITEM', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    66 => ['name' => 'MATTR_REINFORCE_ITEM', 'desc' => 'MATTR_REINFORCE_ITEM', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    65 => ['name' => 'MATTR_NOT_REPARABLE', 'desc' => 'MATTR_NOT_REPARABLE', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
    64 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 6, 'extension' => '', 'sortkey' => 9],
    63 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 5, 'extension' => '', 'sortkey' => 9],
    62 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 4, 'extension' => '', 'sortkey' => 9],
    61 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 3, 'extension' => '', 'sortkey' => 9],
    60 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 2, 'extension' => '', 'sortkey' => 9],
    59 => ['name' => 'MATTR_LUCK', 'desc' => 'Luck (%desc% Time/times)', 'mLevel' => 1, 'extension' => '', 'sortkey' => 9],
    58 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 6, 'extension' => '', 'sortkey' => 4],
    57 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 5, 'extension' => '', 'sortkey' => 4],
    56 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 4, 'extension' => '', 'sortkey' => 4],
    55 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 3, 'extension' => '', 'sortkey' => 4],
    54 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 2, 'extension' => '', 'sortkey' => 4],
    53 => ['name' => 'MATTR_SOLID', 'desc' => 'Steady (%desc% Time/times)', 'mLevel' => 1, 'extension' => '', 'sortkey' => 4],
    52 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 6, 'extension' => '', 'sortkey' => 8],
    51 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 5, 'extension' => '', 'sortkey' => 8],
    50 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 4, 'extension' => '', 'sortkey' => 8],
    49 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 3, 'extension' => '', 'sortkey' => 8],
    48 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 2, 'extension' => '', 'sortkey' => 8],
    47 => ['name' => 'MATTR_ATHANASIA', 'desc' => 'Immortal (%desc% Time/times)', 'mLevel' => 1, 'extension' => '', 'sortkey' => 8],
    46 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 6, 'extension' => '', 'sortkey' => 7],
    45 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 5, 'extension' => '', 'sortkey' => 7],
    44 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 4, 'extension' => '', 'sortkey' => 7],
    43 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 3, 'extension' => '', 'sortkey' => 7],
    42 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 2, 'extension' => '', 'sortkey' => 7],
    41 => ['name' => 'MATTR_RESIST_ZOMBIE', 'desc' => 'ZombieHour %desc%% Reduce', 'mLevel' => 1, 'extension' => '', 'sortkey' => 7],
    40 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 6, 'extension' => '', 'sortkey' => 6],
    39 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 5, 'extension' => '', 'sortkey' => 6],
    38 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 4, 'extension' => '', 'sortkey' => 6],
    37 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 3, 'extension' => '', 'sortkey' => 6],
    36 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 2, 'extension' => '', 'sortkey' => 6],
    35 => ['name' => 'MATTR_RESIST_POISON', 'desc' => 'PosioningHour %desc%% Reduce', 'mLevel' => 1, 'extension' => '', 'sortkey' => 6],
    34 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 6, 'extension' => '', 'sortkey' => 4],
    33 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 5, 'extension' => '', 'sortkey' => 4],
    32 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 4, 'extension' => '', 'sortkey' => 4],
    31 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 3, 'extension' => '', 'sortkey' => 4],
    30 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 2, 'extension' => '', 'sortkey' => 4],
    29 => ['name' => 'MATTR_RESIST_BURN', 'desc' => 'BurnHour %desc%% Reduce', 'mLevel' => 1, 'extension' => '', 'sortkey' => 4],
    28 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 6, 'extension' => '', 'sortkey' => 5],
    27 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 5, 'extension' => '', 'sortkey' => 5],
    26 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 4, 'extension' => '', 'sortkey' => 5],
    25 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 3, 'extension' => '', 'sortkey' => 5],
    24 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 2, 'extension' => '', 'sortkey' => 5],
    23 => ['name' => 'MATTR_RESIST_ESHOCK', 'desc' => 'Electric shockHour %desc%% Reduce', 'mLevel' => 1, 'extension' => '', 'sortkey' => 5],
    22 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 6, 'extension' => '', 'sortkey' => 3],
    21 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 5, 'extension' => '', 'sortkey' => 3],
    20 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 4, 'extension' => '', 'sortkey' => 3],
    19 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 3, 'extension' => '', 'sortkey' => 3],
    18 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 2, 'extension' => '', 'sortkey' => 3],
    17 => ['name' => 'MATTR_RESIST_FROSTBITE', 'desc' => 'Freezing,FrostbiteHour %desc%% Reduce', 'mLevel' => 1, 'extension' => '', 'sortkey' => 3],
    16 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 6, 'extension' => '', 'sortkey' => 1],
    15 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 5, 'extension' => '', 'sortkey' => 1],
    14 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 4, 'extension' => '', 'sortkey' => 1],
    13 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 3, 'extension' => '', 'sortkey' => 1],
    12 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 1],
    11 => ['name' => 'MATTR_STR', 'desc' => 'Str %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 1],
    10 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 6, 'extension' => '', 'sortkey' => 2],
    9 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 5, 'extension' => '', 'sortkey' => 2],
    8 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 4, 'extension' => '', 'sortkey' => 2],
    7 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 3, 'extension' => '', 'sortkey' => 2],
    6 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 2, 'extension' => '', 'sortkey' => 2],
    5 => ['name' => 'MATTR_INT', 'desc' => 'Int %desc% Increase', 'mLevel' => 1, 'extension' => '', 'sortkey' => 2],
    4 => ['name' => 'MATTR_DEC_MAXDUR', 'desc' => 'Maximum Durability %desc% Reduce', 'mLevel' => 4, 'extension' => '', 'sortkey' => 0],
    3 => ['name' => 'MATTR_DEC_MAXDUR', 'desc' => 'Maximum Durability %desc% Reduce', 'mLevel' => 3, 'extension' => '', 'sortkey' => 0],
    2 => ['name' => 'MATTR_DEC_MAXDUR', 'desc' => 'Maximum Durability %desc% Reduce', 'mLevel' => 2, 'extension' => '', 'sortkey' => 0],
    1 => ['name' => 'MATTR_DEC_MAXDUR', 'desc' => 'Maximum Durability %desc% Reduce', 'mLevel' => 1, 'extension' => '', 'sortkey' => 0],
];
